#!/bin/bash 

# Clear logs
# WAS:  Stop run_cameras; clear logs; start run_cameras
# Run via cron after midnight

LOCKDIR="/var/local/hpwren/lock"
LOGDIR="/var/local/hpwren/log"
GETCAMSDIR="/home/hpwren/bin/getcams"

[ -d  $LOGDIR/old ] || mkdir -p  $LOGDIR/old

if [[ -e $LOCKDIR/RUNCAM_PID ]] ;
then
    # Halt getcams system if running
    was_running=1
    $GETCAMSDIR/run_cameras -X
fi

#sleep 5
cp -f  $LOGDIR/*.log  $LOGDIR/runcamlog $LOGDIR/old
for i in $LOGDIR/*.log
do
    cp -f /dev/null $i
done
#sleep 5

if [[ $was_running == 1 ]] ;
then
    # Restart getcams system
    $GETCAMSDIR/run_cameras -I &
    was_running=0
fi

