#!/bin/bash 

# Stop run_cameras; clear logs; start run_cameras
# Run via cron after midnight

LOCKDIR="/var/local/hpwren/lock"
LOGDIR="/var/local/hpwren/log"
GETCAMSDIR="/home/hpwren/bin/getcams"


if [[ -e $LOCKDIR/RUNCAM_PID ]] ;
then
    # Halt getcams system if running
    was_running=1
    $GETCAMSDIR/run_cameras -X
fi

sleep 5
mv -f  $LOGDIR/*.log  $LOGDIR/runcamlog $LOGDIR/old
sleep 5

if [[ $was_running == 1 ]] ;
then
    # Restart getcams system
    $GETCAMSDIR/run_cameras -I &
fi

