apiVersion: batch/v1
kind: Job
metadata:
  name: getcams
  namespace: hpwren
spec:
  template:
    spec:
      containers:
      - name: getcams
        image: gitlab-registry.nautilus.optiputer.net/hpwren/getcams
        command: ["bash", "-c"]
        args: ["sleep infinity"]
        volumeMounts:
        - name: git-repo
          mountPath: /opt/getcams
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            memory: 4Gi
            cpu: "1"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/ghidley/getcams.git
          - /opt/getcams
        volumeMounts:
          - name: git-repo
            mountPath: /opt/getcams
      volumes:
      - name: git-repo
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 5